authors:
  Tim:
    name: Tim Carman
    description: Creator
    avatar: /assets/images/contributors/tim-carman.jpg
  Matt:
    name: Matt Allford
    description: Contributor
    avatar: /assets/images/contributors/matt-allford.jpg
  Jon:
    name: Jonathan Colon
    description: Contributor
    avatar: /assets/images/contributors/jonathan-colon.jpg
